seed: 100 
batch_size: 32
num_workers: 0
use_cuda: True
method: KPGT_Variance_CrossATT #基学习器方案
weight_decay: 0
# Learning_rate: 1e-5 # 基學習器最佳學習率
Learning_rate: 5e-5
Epoch: 50
predict_task: 'Classification'  # regression / Classification  回归还是分类
Patient_test: False

DATA:
  split_task: 'split_data'        # split_data 表示随机划分  AL_cold_split_10_10_START 表示主动学习
                                  # cold_split_data_Unseen_20%_Cell   cold_split_data_Unseen_20%_Drug   cold_split_data_Unseen_30%_Drug_Cell

  source_data_name: 'GDSC2_AUC'   # GDSC_depmap_AUC / GDSC2_AUC / PRISM_AUC / 
  expdim_reduce_method: Variance  # PCA / AE / Variance / correlation+Variance / correlation
  drug_feature_method: KPGT       # GCN / MACCS / ECFP4 / unimol / Pubchem / KPGT / Molformer

  GCN_max_drug_nodes: 290         # 参考的drugban的最大长度设置
  GCN_node_in_feats: 75
  GCN_node_in_embedding: 128
  GCN_drug_padding: True
  GCN_drug_hidden_layer: [128, 128, 128]

  correlation_dim: 799            #  PRISM_AUC_correlation:786 / GDSC2_AUC_correlation:775 / GDSC_depmap_AUC_correlation:799
  variances_dim: 800              #  400/600/800


MODEL:
  attention_dim_size: 32
  HSIC_loss_weight: 0.5
  Kernel_bandwidth: 1


MCAN:
  IFATT: True
  LAYER: 1
  HIDDEN_SIZE: 16
  MULTI_HEAD: 2
  DROPOUT_R: 0
  FF_SIZE: 32             # FF_SIZE = HIDDEN_SIZE * 2
  HIDDEN_SIZE_HEAD: 8       # HIDDEN_SIZE_HEAD = HIDDEN_SIZE / MULTI_HEAD


AL:

  # AL_START: ABAB        # 主动学习方法
  AL_TASK: True
  total_budget: 2000  # 总预算
  num_rounds: 10           # 主动学习轮数   # 总预算/主动学习轮数  最好是偶数，否则计算不确定样本时的max_length可能会有问题
  Lambda: 10

  retrain: True          # 每轮主动学习是否重新训练

  Cold_start: False      # False True
  AL_START_DATA: 200     # 启动数据 
  AL_START_Epoch: 50      # 数据训练轮数 
  AL_early_stop_num: 5    # 每轮主动学习早停设置       
  
  uncertainty_range: 0.05     # 不确定数据在未标注内容中的挑选区域 
  certainty_range: 0.1      # 确定数据挑选区域
  KMeans_center_nums: 500    # 最好是偶数，否则计算不确定样本时的max_length可能会有问题
  certainty_confidence: 1    # 第一轮是純Kmeans挑出来的，数据多样性(冷启动)

  Pseudo_task: False  # False True
  Pseudo_lambda: 0.1

  diversity_method: 'HNSW'  # 多样性挑选策略  'KMeans'  'HNSW'  
  HNSW_n_neighbors: 5000

  imbalance_strategy: False    # 是否使用样本不平衡策略
  cold_start_strategy: 'uncertainty'   # 冷启动方式  'uncertainty'  /  'diversity' / 'hybrid'