seed: 100 
batch_size: 32
num_workers: 0
use_cuda: True
method: KPGT_Variance_CrossATT 
weight_decay: 0
Learning_rate: 5e-5
Epoch: 50
predict_task: 'Classification'  # regression / Classification 
Patient_test: False

DATA:
  split_task: 'split_data'      
  source_data_name: 'GDSC2_AUC'   
  expdim_reduce_method: Variance  # PCA / AE / Variance / correlation+Variance / correlation
  drug_feature_method: KPGT       # GCN / MACCS / ECFP4 / unimol / Pubchem / KPGT / Molformer

  GCN_max_drug_nodes: 290 
  GCN_node_in_feats: 75
  GCN_node_in_embedding: 128
  GCN_drug_padding: True
  GCN_drug_hidden_layer: [128, 128, 128]

  variances_dim: 800              #  400/600/800


MODEL:
  attention_dim_size: 32
  HSIC_loss_weight: 0.5
  Kernel_bandwidth: 1


MCAN:
  IFATT: True
  LAYER: 1
  HIDDEN_SIZE: 16
  MULTI_HEAD: 2
  DROPOUT_R: 0
  FF_SIZE: 32             # FF_SIZE = HIDDEN_SIZE * 2
  HIDDEN_SIZE_HEAD: 8       # HIDDEN_SIZE_HEAD = HIDDEN_SIZE / MULTI_HEAD


AL:
  AL_TASK: True
  total_budget: 2000        # 总预算
  num_rounds: 10            # 主动学习轮数
  Lambda: 10

  retrain: True          # 每轮主动学习是否重新训练
  Cold_start: False      # False True
  AL_START_DATA: 200     # 启动数据 
  AL_START_Epoch: 50      # 数据训练轮数 
  AL_early_stop_num: 5    # 每轮主动学习早停设置       
  